name: Code Linting on Pull-Requests

on:
  pull_request:
    branches: [ master, release* ]

jobs:
  clang-tidy-review:
    runs-on: ubuntu-latest

    steps:
      - name: compiler versions
        run: |
          echo $(gcc --version)
          echo $(clang --version)

      - name: Install iceoryx dependencies and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y libacl1-dev libncurses5-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15 all ## uses clang version 15
          sudo rm /usr/bin/clang
          sudo rm /usr/bin/clang++
          sudo rm /usr/bin/clang-tidy
          sudo ln -s /usr/bin/clang-15 /usr/bin/clang
          sudo ln -s /usr/bin/clang++-15 /usr/bin/clang++
          sudo ln -s /usr/bin/clang-tidy-15 /usr/bin/clang-tidy

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: clang-tidy for all files in "clang-tidy-files-to-scan.txt"
        run: ./tools/scripts/clang_tidy_check.sh scan_list clang-tidy-files-to-scan.txt

  verify-links-in-markdown-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          fail: true
          args: --verbose --no-progress './**/*.md' --github-token ${{secrets.GITHUB_TOKEN}} --max-concurrency 1
